RUN_STRINGS = (
    "Berlari ke Thanos..",
    "Berlari jauh, jauh dari bumi..",
    "Berlari lebih cepat dari Bolt karena aku pengguna bot !!",
    "Berlari ke pluto..",
    "Grup ini terlalu berbahaya untuk ditangani, aku harus lari.",
    "`Berlari Dari Orang Yang Bau Sawi 😬`",
    "Aku sangat lelah untuk berlari dan mengejarmu 💔",
    "Aku pergi dulu",
    "Saya hanya berjalan pergi, karena saya terlalu gemuk untuk lari.",
    "Saya Cape!",
    "Larii Disini Bau Sawii 😭",
    "Saya lari karena saya sangat gabut.",
    "Lari... \nkarena diet bukanlah pilihan.",
    "Berlari Cepat Dari Orang Gila",
    "Jika kamu ingin menangkapku, kamu harus cepat... \nJika kamu ingin tinggal bersamaku, kamu harus menjadi orang yang baik... \nTapi jika kamu ingin melewati aku... \nKamu pasti bercanda. ",
    "Siapapun dapat berlari seratus meter, itu hitungan empat puluh dua ribu dua ratus berikutnya.",
    "Mengapa semua orang ini mengikuti saya?",
    "Apakah anak-anak masih mengejarku?",
    "Berlari Sekencang Super Dede.. Apakah Sopan Begitu?",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MASHA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{hits} {victim} dengan {item}.",
    "{hits} {victim} di wajah dengan {item}.",
    "{hits} {victim} sekitar sedikit dengan {item}.",
    "{throws} {item} ke {Victim}.",
    "mengambil {item} dan {throws} ke wajah {victim}.",
    "Menusuk {victim} dengan tombak cinta.",
    "{throws} beberapa {item} ke {victim}.",
    "mengambil {item} dan {throws} ke wajah {victim}.",
    "meluncurkan {item} ke arah umum {korban}.",
    "duduk di wajah {victim} sambil membanting {item}.",
    "mulai menampar {victim} dengan konyol dengan {item}.",
    "pin {victim} ke bawah dan berulang kali {hits} mereka dengan {item}.",
    "mengambil {item} dan {hits} {victim} dengannya.",
    "mulai menampar {victim} dengan konyol dengan {item}.",
    "menahan {victim} dan berulang kali {hits} mereka dengan {item}.",
    "memukul {victim} dengan {item}.",
    "mengambil {item} dan {hits} {victim} dengannya.",
    "mengikat {victim} ke kursi dan {throws} {item} padanya.",
    "{hits} {victim} {where} dengan {item}.",
    "mengikat {victim} ke tiang dan mencambuk mereka {where} dengan {item}."
    "memberikan dorongan ramah untuk membantu {victim} belajar berenang di lahar.",
    "mengirim {victim} ke /laut /lahar.",
    "mengirim {victim} ke lubang memori.",
    "memenggal {victim}.",
    "melemparkan {victim} dari sebuah gedung.",
    "mengganti semua musik {victim} dengan lagu iri bilang bos.",
    "spam email {victim}.",
    "membuat {victim} depresi.",
    "menampar {victim} tanpa apa-apa.",
    "pukul {victim} dengan pesawat garuda.",
    "memukul kepala {victim}.",
    "taruh {victim} di tong sampah.",
    "Menendang {victim} dan melemparnya ke sungai.",
    "letakkan {victim} di rumah hantu.",
    "menampar {victim} dengan tongkat besi!",

)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "Saya Disini!",
)

ITEMS = (
    "Tabung Gas",
    "Televisi 42 In",
    "Raket",
    "Raket Nyamuk",
    "Kaca",
    "Buku",
    "Ringgis",
    "Telur",
    "Jarum",
    "Monitor Tabung",
    "Obeng",
    "Almunium",
    "Emas",
    "Printer",
    "Speaker",
    "Gas Lpg",
    "Tangki Bensin",
    "Tandon Air",
    "Bola Boling",
    "Laptop",
    "Hardisk Rusak",
    "Wajan Panas",
    "Virus Corona",
    "Meja Kantor",
    "Meja Arsip",
    "Lemari",
    "Ember Besi",
    "Besi Beton",
    "Timah Panas",
    "Harimau",
    "Batu Krikil",
    "Makanan Basi",
    "Pesawat AirBus",
    "Roket Nasa",
    "Satelit Nasa",
    "Matahari",
    "Meteor",
    "Berkas Kantor",
    "Beton panas",
    "Cermin",
    "Batu Giok",
    "Botol",
    "Nezuko",
    "Kaset Pita",
    "Tiang Jemuran",
    "Pisau Lipat",
    "Bongkahan Es ",
    "Asteroid", 
)

THROW = (
    "Melempar",
    "Melemparkan",
)

HIT = (
    "Memukul",
    "Melemparkan",
    "Memukuli",
    "Menendang",
    "Menampar",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Ya.", "Tidak.", "Mungkin.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
