TRUTH = (
    "Kalau kamu bisa jadi tidak terlihat, apa hal pertama yang akan kamu lakukan?",
    "Apa rahasia yang kamu sembunyikan dari orangtuamu?",
    "Siapa orang yang diam-diam kamu sukai?",
    "Siapa orang terakhir yang kamu kepoin di media sosial?",
    "Kalau ada jin yang memberikanmu tiga permohonan, apa yang kamu inginkan?",
    "Siapa orang di antara kita yang menurutmu bisa lolos dari kiamat zombie dan siapa yang akan mati duluan? Beri tahu alasannya!",
    "Apa tontonan favoritmu saat masih kecil?",
    "Siapa orang yang paling sering kamu chat?",
    "Apa kebohongan terbesar yang pernah kamu katakan kepada orangtuamu?",
    "Apa mimpi paling aneh yang pernah kamu alami?",
    "Apa hal yang paling membuatmu merasa insecure?",
    "Kapan terakhir kali kamu ngompol?",
    "Menurutmu, hewan apa yang terlihat paling mirip denganmu?",
    "Di antara kita, siapa orang yang paling kamu suka dalam konteks romantis?",
    "Di antara kita, siapa orang yang menurutmu paling baik dan paling buruk sifatnya?",
    "Siapa mantan terindahmu?",
    "Siapa orang yang ingin kamu jadikan istri/suami?",
    "Apakah kamu pernah melakukan ghosting?", 
    "Apa penyesalan terburukmu?",
    "Berapa jumlah mantanmu?",
    "film terakhir yang membuatmu menangis?",
    "Apa satu hal yang kamu takut kehilangan.",
)

DARE = (
    "Lakukan rap gaya bebas selama 3 menit.",
    "Biarkan orang lain membuat status menggunakan akun sosial mediamu.",
    "Berikan ponselmu kepada salah satu di antara temanmu dan biarkan orang tersebut mengirim satu pesan kepada siapapun yang dia mau.",
    "Baca atau buatlah puisi dengan tema (alam/cinta/sesuatu yang absurd) selama waktu lima menit kemudian kirimkan di grup.",
    "Lihatin chat paling memalukan yang masih kamu simpan.",
    "Telepon orangtuamu dan bilang bahwa kamu sedang kangen kepada mereka.",
    "Katakan ‘meong’ di setiap akhir kalimat selama satu jam.",
    "Tirukan seorang selebriti sampai ada yang bisa menebak.",
    "Pesan makanan secara online dan buat pesanan tersebut diberikan kembali kepada driver yang mengantarkan pesanan yang sudah kamu bayar.", 
    "Pilih seseorang digrup dengan nickname awalan E menjadi bestiemu.",
    "Gunakan penutup mata lalu raba muka salah satu di antara kita sampai kamu bisa menebak siapa orang itu.",
    "Ungkapkan perasaanmu kepada bestiemu digrup.",
    "Spam kata ayang digrup sampai 20 kali.",
    "Gunakan Kata Sayang disetiap pesan yang kamu kirim digrup.",
    "Gunakan #Sayajelek dibelakang namamu selama satu jam.",
    "Katakan I love you ke orang yang terakhir mengirim pesan digrupmu.",
    "Kirim Kata yang kamu salin terakhir di grup.",
    "Telepon seorang teman dan katakan selamat ulang tahun sambil menyanyikan lagu.",
    "Bernyanyi lagu yang tidak kamu sukai di vcg.",
    "Ulangi setiap perkataan orang yang digrup selama 30 menit.",
    "Perlihatkan chat paling lucu yang pernah kamu dapatkan.",
    "Katakan dua hal jujur tentang semua orang dalam grup.",
    "Kirim cover lagu favoritmu.",
    "Cobalah membuat grup tertawa secepat mungkin.",
    
)
